version: "3.8"

services:
  db:
    image: kartoza/postgis:13-3.1
    environment:
      - POSTGRES_DB=postgres,data_pipeline
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"    
  frontend:
    build:
      context: packages/frontend
      dockerfile: Dockerfile.debug
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./packages/frontend/.:/app
  backend:
    build:
      context: packages/backend
    ports:
      - 3001:3000
      - 9240:9229
    environment:
      service_config: "./src/utils/config/local-env.yml"
    depends_on:
      flyway:
        condition: service_completed_successfully
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/data_pipeline -schemas=postgres -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./packages/backend/src/utils/migrations:/flyway/sql
    depends_on:
      db:
        condition: service_healthy