export enum ModalTypes {
  HELP = 'HELP',
  FOCUS = 'FOCUS',
  EMPLOYEE_HUB = 'EMPLOYEE_HUB',
  CONFIRMATION = 'CONFIRMATION',
  LEADERSHIP_IMPACT = 'LEADERSHIP_IMPACT',
  LEADERSHIP_IMPACT_ON_EMPLOYEE = 'LEADERSHIP_IMPACT_ON_EMPLOYEE',
  METRIC = 'METRIC',
  ACTION_PLAN = 'ACTION_PLAN',
  NEW_PULSE = 'NEW_PULSE',
  PULSE_RESPONSE = 'PULSE_RESPONSE',
}
