export enum StringRole {
  EXECUTIVE = 'EXECUTIVE',
  HR_EXECUTIVE = 'HR_EXECUTIVE',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  IT = 'IT',
  USER = 'USER',
}

export enum PulseFFValues {
  SHOW_ONLY_PULSES = 'SHOW_ONLY_PULSES',
  SHOW_MENU_WITH_PULSES = 'SHOW_MENU_WITH_PULSES',
  SHOW_MENU_WITHOUT_PULSES = 'SHOW_MENU_WITHOUT_PULSES',
}

export enum EVENT_ORIGIN {
  MIRAMAR = 'Miramar',
  PACIFICA = 'Pacifica',
}
