services:
  - postgres:12.2-alpine

include:
  project: 'montara/devops/ci-cd'
  ref: master
  file: 'common/node-gitlab-ci.yml'

variables:
  SERVICE_ADMIN: "True"
  COVERAGE: "78"
  E2ECOVERAGE: "58"
  CI: 'True'
  POSTGRES_DB: data_pipeline
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST_AUTH_METHOD: trust
  service_config: "./src/utils/config/ci.yml"

stages:
  - install_dependencies
  - build
  - test
  - dockerbuild

e2e:
  stage: test
  image: node:14
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - node_modules/
      - .npm/
  only:
    - merge_requests
  script:
    - echo "Te2e esting App"
    - echo "Test with coverage!"
    - echo "//gitlab.com/api/v4/projects/25331249/packages/npm/:_authToken=${GITLAB_ACCESS_TOKEN}">.npmrc
    - echo "//gitlab.com/api/v4/packages/npm/:_authToken=${GITLAB_ACCESS_TOKEN}">>.npmrc
    - echo "@montara:registry=https://gitlab.com/api/v4/packages/npm/">>.npmrc
    - npm i -g @nestjs/cli
    - npm i
    - npm run test:e2e-ci -- --coverage --watchAll=false --coverageThreshold='{"global":{"statements":"$E2ECOVERAGE"}}'
