version: '3'
services:
  db:
    hostname: postgres
    image: 'postgres'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=data_pipeline
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6004:5432
    networks:
      - data-pipeline-test-net  
networks:
  data-pipeline-test-net:
    driver: bridge
