version: '3'
services:
  db:
    hostname: localhost
    image: 'kartoza/postgis:13-3.1'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=data_pipeline
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6004:5432
    networks:
      - data-pipeline-test-net  
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/data_pipeline -schemas=postgres -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./src/utils/migrations:/flyway/sql
    networks:
      - data-pipeline-test-net  
    depends_on:
      db:
        condition: service_healthy
networks:
  data-pipeline-test-net:
    driver: bridge
