name: Frontend deploy github actions
run-name: ${{ github.actor }} run monorepo cd for frontend 🚀
# on:
#   push:
#     branches: [main]
on: [push]

jobs:
  frontend-pipeline:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@v1.0.1
        id: changed-frontend
        with:
          paths: packages/frontend
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Log in to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
          DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
        # if: steps.changed-frontend.outputs.changed == 'true'
        run: |
          docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - name: build docker
        working-directory: ./packages/frontend
        # if: steps.changed-frontend.outputs.changed == 'true'
        run: docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/lucia-frontend .
      - name: deploy docker
        working-directory: ./packages/frontend
        # if: steps.changed-frontend.outputs.changed == 'true'
        run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/lucia-frontend
      - run: echo "🍏 This job's status is ${{ job.status }}."
